// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetRoomList.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	GetRoomList.proto
	HeartBeat.proto
	Login.proto

It has these top-level messages:
	GetRoomList_ToS
	GetRoomList_ToC
	HeartBeat_ToS
	Login_ToS
	Login_ToC
*/
package proto

import proto1 "QQdemo/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRoomList_ToS struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRoomList_ToS) Reset()                    { *m = GetRoomList_ToS{} }
func (m *GetRoomList_ToS) String() string            { return proto1.CompactTextString(m) }
func (*GetRoomList_ToS) ProtoMessage()               {}
func (*GetRoomList_ToS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRoomList_ToS) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

type GetRoomList_ToC struct {
	Roomid           *string `protobuf:"bytes,1,req,name=roomid" json:"roomid,omitempty"`
	Roomname         *string `protobuf:"bytes,2,req,name=roomname" json:"roomname,omitempty"`
	Roompeople       *int32  `protobuf:"varint,3,req,name=roompeople" json:"roompeople,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRoomList_ToC) Reset()                    { *m = GetRoomList_ToC{} }
func (m *GetRoomList_ToC) String() string            { return proto1.CompactTextString(m) }
func (*GetRoomList_ToC) ProtoMessage()               {}
func (*GetRoomList_ToC) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *GetRoomList_ToC) GetRoomid() string {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return ""
}

func (m *GetRoomList_ToC) GetRoomname() string {
	if m != nil && m.Roomname != nil {
		return *m.Roomname
	}
	return ""
}

func (m *GetRoomList_ToC) GetRoompeople() int32 {
	if m != nil && m.Roompeople != nil {
		return *m.Roompeople
	}
	return 0
}

func init() {
	proto1.RegisterType((*GetRoomList_ToS)(nil), "proto.GetRoomList_ToS")
	proto1.RegisterType((*GetRoomList_ToC)(nil), "proto.GetRoomList_ToC")
}

func init() { proto1.RegisterFile("GetRoomList.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{  //改正
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x74, 0x4f, 0x2d, 0x09,
	0xca, 0xcf, 0xcf, 0xf5, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0xca, 0x5c, 0xfc, 0x48, 0x72, 0xf1, 0x21, 0xf9, 0xc1, 0x42, 0x02, 0x5c, 0xcc, 0xa5,
	0x99, 0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x52, 0x2a, 0xba, 0x22, 0x67,
	0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xfc, 0xfc, 0x5c, 0xb8, 0x3a, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0x03,
	0xc4, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x02, 0xcb, 0xc0, 0xf9, 0x42, 0x72, 0x5c, 0x5c, 0x20,
	0x76, 0x41, 0x6a, 0x7e, 0x41, 0x4e, 0xaa, 0x04, 0xb3, 0x02, 0x93, 0x06, 0x6b, 0x10, 0x92, 0x08,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x54, 0x65, 0xe1, 0xa6, 0x00, 0x00, 0x00,
}
