// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Login.proto

package proto

import proto1 "QQdemo/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Login_ToS struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login_ToS) Reset()                    { *m = Login_ToS{} }
func (m *Login_ToS) String() string            { return proto1.CompactTextString(m) }
func (*Login_ToS) ProtoMessage()               {}
func (*Login_ToS) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Login_ToS) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

type Login_ToC struct {
	IsOk             *bool  `protobuf:"varint,1,req,name=isOk" json:"isOk,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Login_ToC) Reset()                    { *m = Login_ToC{} }
func (m *Login_ToC) String() string            { return proto1.CompactTextString(m) }
func (*Login_ToC) ProtoMessage()               {}
func (*Login_ToC) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Login_ToC) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return false
}

func init() {
	proto1.RegisterType((*Login_ToS)(nil), "proto.Login_ToS")
	proto1.RegisterType((*Login_ToC)(nil), "proto.Login_ToC")
}

func init() { proto1.RegisterFile("Login.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf6, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xb2, 0x5c, 0x9c, 0x60,
	0xd1, 0xf8, 0x90, 0xfc, 0x60, 0x21, 0x01, 0x2e, 0xe6, 0xd2, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x26,
	0x0d, 0xce, 0x20, 0x10, 0x53, 0x49, 0x1e, 0x21, 0xed, 0x2c, 0x24, 0xc4, 0xc5, 0x92, 0x59, 0xec,
	0x9f, 0x0d, 0x96, 0xe7, 0x08, 0x02, 0xb3, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0x43, 0xf1,
	0x95, 0x54, 0x00, 0x00, 0x00,
}
